---
title: "php 2650 hw5"
date: "4/22/2018"
output: html_document
---

```{r}
library(data.table)
require(Matrix)
require(data.table)
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
require(xgboost)
library(klaR)
library(stringr)
require(reshape)

```


```{r}
# read in test data
#test <- fread("Predict_NoShow_PrivateTest_WithoutLabels.csv", header = TRUE)
#test2 <- fread("Predict_NoShow_PublicTest_WithoutLabels.csv", header = TRUE)

# read in train data
train_total <- fread("/Users/weiqipan/Desktop/Predict_NoShow_Train.csv", header = TRUE)
id <- train_total[,1] # delete ID column
train_total <- train_total[,-1] # save ID column for further use 
# date of appointment was made
date_made <- data.frame(train_total$DateAppointmentWasMade)
colnames(date_made) <- "date_made"
date_made_table <- transform(date_made, date_made=colsplit(date_made, split="-", names=c("year","month_made","day")))
date_made_month <- date_made_table[,1][2]
# date of appointment
date <- data.frame(train_total$DateOfAppointment)
colnames(date) <- "date"
date_table <- transform(date, date=colsplit(date, split="-", names=c("year","month","day")))
date_month <- date_table[,1][2]
# add back to dataframe
train<-cbind(date_made_month,train_total)
train<-cbind(date_month,train)
train<-train[,-5]
train<-train[,-5]
```

```{r}
df <- data.table(train, keep.rownames = F)
# convert dataframe to sparse matrix, which is fit for XGBOOST
sparse_matrix <- sparse.model.matrix(Status~.-1, data = df)
# define output vector, which is the y column
output_vector = df[,Status] == "No-Show"
# parameters could be redefined after discussio
bst <- xgboost(data =sparse_matrix , label = output_vector, max.depth =15, 
                     eta = 0.1, nthread=3, nround = 50, subsample=0.8, colsample_bytree=0.5, objective="binary:logistic",eval_metric="logloss")
# another way to seperate dataset 
#dtrain <- xgb.DMatrix(data = sparse_matrix, label = output_vector)
#bstDMatrix <- xgboost(data = dtrain, max.depth = 2, eta = 1, nthread = 2, nround = 20, objective = "binary:logistic")

# bst <- xgb.train(data=dtrain, booster = "gblinear", max.depth=2, nthread = 2, nround=2,  eval.metric = "error", eval.metric = "logloss", objective = "binary:logistic")

```



```{r}
# build model for prediction
# have not tested result
test <- fread("~/Desktop/Predict_NoShow_PrivateTest_WithoutLabels.csv", header = TRUE)
test2 <- fread("~/Desktop/Predict_NoShow_PublicTest_WithoutLabels.csv", header = TRUE)

id_private <- test$ID
test <- test[,-1] # save ID column for further use 
# date of appointment was made
date_made <- data.frame(test$DateAppointmentWasMade)
colnames(date_made) <- "date_made"
date_made_table <- transform(date_made, date_made=colsplit(date_made, split="-", names=c("year","month_made","day")))
date_made_month <- date_made_table[,1][2]
# date of appointment
date <- data.frame(test$DateOfAppointment)
colnames(date) <- "date"
date_table <- transform(date, date=colsplit(date, split="-", names=c("year","month","day")))
date_month <- date_table[,1][2]
# add back to dataframe
test<-cbind(date_made_month,test)
test<-cbind(date_month,test)
test<-test[,-5]
test<-test[,-5]


fake.outcome <- c(rep(1,50),rep(1,50))
test$Status <- fake.outcome
dftest <- data.table(test, keep.rownames = F)
sparse_matrix.test <- sparse.model.matrix(Status~.-1, data = dftest)
pred <- predict(bst, sparse_matrix.test)
#prediction <- as.numeric(pred > 0.5)
upload_private <- cbind(id_private, pred)
```

```{r}
id_public <- test2$ID
test2 <- test2[,-1] # delete ID column# date of appointment was made
# date of appointment was made
date_made <- data.frame(test2$DateAppointmentWasMade)
colnames(date_made) <- "date_made"
date_made_table <- transform(date_made, date_made=colsplit(date_made, split="-", names=c("year","month_made","day")))
date_made_month <- date_made_table[,1][2]
# date of appointment
date <- data.frame(test2$DateOfAppointment)
colnames(date) <- "date"
date_table <- transform(date, date=colsplit(date, split="-", names=c("year","month","day")))
date_month <- date_table[,1][2]
# add back to dataframe
test2<-cbind(date_made_month,test2)
test2<-cbind(date_month,test)
test2<-test2[,-5]
test2<-test2[,-5]

test2$Status <- fake.outcome
dftest2 <- data.table(test2, keep.rownames = F)
sparse_matrix.test2 <- sparse.model.matrix(Status~.-1, data = dftest2)
pred2 <- predict(bst, sparse_matrix.test2)
#prediction <- as.numeric(pred > 0.5)
upload_public <- cbind(id_public, pred2)

write.table(upload_private, file = "private.csv", sep = ",", col.names=FALSE, row.names = FALSE)
write.table(upload_public, file = "public.csv", sep = ",", col.names=FALSE, row.names = FALSE)




```

